# Generated by Django 5.2.8 on 2025-12-28 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('categorie', models.CharField(choices=[('aviation', 'Aviation civile'), ('avions', 'Grands avions'), ('operations', 'Opérations militaires')], default='aviation', max_length=50)),
                ('date_publication', models.DateField()),
                ('auteur', models.CharField(default="L'Air du Vol", max_length=100)),
                ('resume', models.TextField(help_text="Résumé de l'article")),
                ('image_principale', models.URLField(blank=True, help_text="URL de l'image principale")),
                ('theme1_titre', models.CharField(blank=True, max_length=200)),
                ('theme1_section_a_titre', models.CharField(blank=True, max_length=200)),
                ('theme1_section_a_texte', models.TextField(blank=True)),
                ('theme1_section_b_titre', models.CharField(blank=True, max_length=200)),
                ('theme1_section_b_texte', models.TextField(blank=True)),
                ('theme2_titre', models.CharField(blank=True, max_length=200)),
                ('theme2_section_a_titre', models.CharField(blank=True, max_length=200)),
                ('theme2_section_a_texte', models.TextField(blank=True)),
                ('theme2_section_b_titre', models.CharField(blank=True, max_length=200)),
                ('theme2_section_b_texte', models.TextField(blank=True)),
                ('theme3_titre', models.CharField(blank=True, max_length=200)),
                ('theme3_section_a_titre', models.CharField(blank=True, max_length=200)),
                ('theme3_section_a_texte', models.TextField(blank=True)),
                ('theme3_section_b_titre', models.CharField(blank=True, max_length=200)),
                ('theme3_section_b_texte', models.TextField(blank=True)),
                ('conclusion_titre', models.CharField(default='Conclusion', max_length=200)),
                ('conclusion_texte', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='ImageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('legende', models.CharField(blank=True, max_length=300)),
                ('ordre', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='donnelouis.article')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
