# Generated by Django 5.2.8 on 2026-01-03 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnelouis', '0003_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lien',
            options={},
        ),
        migrations.CreateModel(
            name='ForumSujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('categorie', models.CharField(choices=[('general', 'Général'), ('technique', 'Technique'), ('aviation', 'Aviation'), ('actualites', 'Actualités')], default='general', max_length=50)),
                ('contenu', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('vues', models.IntegerField(default=0)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets_forum', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sujet de forum',
                'verbose_name_plural': 'Sujets de forum',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ForumReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='donnelouis.forumsujet')),
            ],
            options={
                'verbose_name': 'Réponse de forum',
                'verbose_name_plural': 'Réponses de forum',
                'ordering': ['date_creation'],
            },
        ),
    ]
