# Generated by Django 5.2.8 on 2026-01-05 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnelouis', '0006_anonymous_contributions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('type_avion', models.CharField(choices=[('civil', 'Avion civil'), ('militaire', 'Avion militaire'), ('historique', 'Avion historique'), ('leger', 'Avion léger'), ('siege', 'Siège éjectable')], max_length=50)),
                ('pays_origine', models.CharField(max_length=100)),
                ('description_courte', models.CharField(help_text="Résumé court de l'avion", max_length=300)),
                ('description_longue', models.TextField(help_text='Description détaillée')),
                ('longueur', models.CharField(blank=True, help_text='Ex: 70.5 m', max_length=100)),
                ('envergure', models.CharField(blank=True, help_text='Ex: 64.4 m', max_length=100)),
                ('hauteur', models.CharField(blank=True, help_text='Ex: 19.4 m', max_length=100)),
                ('masse_a_vide', models.CharField(blank=True, help_text='Ex: 178 000 kg', max_length=100)),
                ('masse_max', models.CharField(blank=True, help_text='Ex: 412 000 kg', max_length=100)),
                ('vitesse_max', models.CharField(blank=True, help_text='Ex: 950 km/h', max_length=100)),
                ('plafond', models.CharField(blank=True, help_text='Ex: 12 500 m', max_length=100)),
                ('autonomie', models.CharField(blank=True, help_text='Ex: 5 000 km', max_length=100)),
                ('moteurs', models.CharField(blank=True, help_text='Ex: 4 x General Electric CF6', max_length=200)),
                ('capacite_passagers', models.IntegerField(blank=True, null=True)),
                ('premiere_creation', models.IntegerField(blank=True, help_text='Année de création', null=True)),
                ('premier_vol', models.IntegerField(blank=True, help_text='Année du premier vol', null=True)),
                ('mise_en_service', models.IntegerField(blank=True, help_text='Année de mise en service', null=True)),
                ('image_principale', models.URLField(help_text="URL de l'image principale")),
                ('image_profil', models.URLField(blank=True, help_text="Vue de profil de l'avion")),
                ('image_interieur', models.URLField(blank=True, help_text="Intérieur de l'avion")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avion',
                'verbose_name_plural': 'Avions',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur_nom', models.CharField(blank=True, help_text='Nom si non connecté', max_length=100)),
                ('auteur_email', models.EmailField(blank=True, help_text='Email si non connecté', max_length=254)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('approuve', models.BooleanField(default=True, help_text='À modérer si false')),
            ],
            options={
                'verbose_name': 'Commentaire article',
                'verbose_name_plural': 'Commentaires article',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ArticleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(choices=[('spam', 'Spam'), ('offensant', 'Contenu offensant'), ('inexact', 'Information inexacte'), ('publicite', 'Publicité non autorisée'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Détails du signalement')),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False, help_text='Signalement traité par modérateur')),
            ],
            options={
                'verbose_name': 'Signalement article',
                'verbose_name_plural': 'Signalements article',
                'ordering': ['-date_signalement'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article favori',
                'verbose_name_plural': 'Articles favoris',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='OfflineCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cache', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cache offline',
                'verbose_name_plural': 'Caches offline',
                'ordering': ['-date_cache'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Courte bio personnelle', max_length=500)),
                ('avatar_url', models.URLField(blank=True, help_text="URL de l'avatar")),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nombre_articles_lus', models.IntegerField(default=0)),
                ('nombre_posts_forum', models.IntegerField(default=0)),
                ('nombre_commentaires', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateur',
            },
        ),
        migrations.RemoveConstraint(
            model_name='forumvote',
            name='unique_vote_per_user',
        ),
        migrations.AlterField(
            model_name='forumreponse',
            name='auteur_email',
            field=models.EmailField(blank=True, help_text='Email si non connecté', max_length=254),
        ),
        migrations.AlterField(
            model_name='forumreponse',
            name='auteur_nom',
            field=models.CharField(blank=True, help_text='Nom si non connecté', max_length=100),
        ),
        migrations.AlterField(
            model_name='forumsujet',
            name='auteur_email',
            field=models.EmailField(blank=True, help_text='Email si non connecté', max_length=254),
        ),
        migrations.AlterField(
            model_name='forumsujet',
            name='auteur_nom',
            field=models.CharField(blank=True, help_text='Nom si non connecté', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='forumvote',
            unique_together={('reponse', 'utilisateur')},
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='donnelouis.article'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlereport',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='donnelouis.article'),
        ),
        migrations.AddField(
            model_name='articlereport',
            name='signaleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='donnelouis.article'),
        ),
        migrations.AddField(
            model_name='favoritearticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_favoris', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offlinecache',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donnelouis.aircraft'),
        ),
        migrations.AddField(
            model_name='offlinecache',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donnelouis.article'),
        ),
        migrations.AddField(
            model_name='offlinecache',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donnelouis.media'),
        ),
        migrations.AddField(
            model_name='offlinecache',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_cache', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favoritearticle',
            unique_together={('user', 'article')},
        ),
    ]
