# Generated by Django 5.2.8 on 2026-01-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnelouis', '0007_aircraft_articlecomment_articlereport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('constructeur', models.CharField(blank=True, max_length=200)),
                ('type_avion', models.CharField(blank=True, max_length=100)),
                ('annee_premier_vol', models.IntegerField(blank=True, null=True)),
                ('capacite', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image_principale', models.URLField(blank=True, help_text="URL de l'image principale")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.RemoveField(
            model_name='offlinecache',
            name='aircraft',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date_envoi',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lu',
        ),
        migrations.DeleteModel(
            name='Aircraft',
        ),
    ]
