# Generated by Django 5.2.8 on 2026-01-05 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnelouis', '0008_avion_remove_offlinecache_aircraft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avion',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Avion', 'verbose_name_plural': 'Avions'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_envoi'], 'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.RemoveField(
            model_name='avion',
            name='date_envoi',
        ),
        migrations.RemoveField(
            model_name='avion',
            name='lu',
        ),
        migrations.AddField(
            model_name='contact',
            name='date_envoi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
