# Generated by Django 5.2.8 on 2026-01-05 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnelouis', '0009_alter_avion_options_alter_contact_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False)),
                ('auteur_du_commentaire_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='donnelouis.articlecomment')),
            ],
            options={
                'verbose_name': 'Notification commentaire',
                'verbose_name_plural': 'Notifications commentaires',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Pour utilisateurs non connectés', max_length=40)),
                ('type_notif', models.CharField(choices=[('forum_reponse', 'Réponse au forum'), ('forum_mention', 'Mention au forum'), ('article_nouveau', 'Nouvel article'), ('media_nouveau', 'Nouveau média'), ('catalogue_nouveau', 'Nouvel avion'), ('commentaire_reponse', 'Réponse à votre commentaire'), ('auth_required', 'Créer un compte')], max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donnelouis.article')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donnelouis.media')),
                ('sujet_forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donnelouis.forumsujet')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
