# Generated by Django 5.2.8 on 2026-01-06 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnelouis', '0010_commentnotification_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vote', models.IntegerField(choices=[(1, "J'aime"), (-1, "J'aime pas")], default=1)),
                ('date_vote', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='donnelouis.article')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like article',
                'verbose_name_plural': 'Likes articles',
                'unique_together': {('article', 'utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='ForumReponseLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vote', models.IntegerField(choices=[(1, "J'aime"), (-1, "J'aime pas")], default=1)),
                ('date_vote', models.DateTimeField(auto_now_add=True)),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='donnelouis.forumreponse')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like réponse forum',
                'verbose_name_plural': 'Likes réponses forum',
                'unique_together': {('reponse', 'utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='ForumSujetLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vote', models.IntegerField(choices=[(1, "J'aime"), (-1, "J'aime pas")], default=1)),
                ('date_vote', models.DateTimeField(auto_now_add=True)),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='donnelouis.forumsujet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like sujet forum',
                'verbose_name_plural': 'Likes sujets forum',
                'unique_together': {('sujet', 'utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='MediaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vote', models.IntegerField(choices=[(1, "J'aime"), (-1, "J'aime pas")], default=1)),
                ('date_vote', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='donnelouis.media')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like média',
                'verbose_name_plural': 'Likes médias',
                'unique_together': {('media', 'utilisateur')},
            },
        ),
    ]
