# Generated by Django 5.2.8 on 2026-01-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donnelouis', '0011_articlelike_forumreponselike_forumsujetlike_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forumreponselike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='forumreponselike',
            name='reponse',
        ),
        migrations.RemoveField(
            model_name='forumreponselike',
            name='utilisateur',
        ),
        migrations.AlterUniqueTogether(
            name='forumsujetlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='forumsujetlike',
            name='sujet',
        ),
        migrations.RemoveField(
            model_name='forumsujetlike',
            name='utilisateur',
        ),
        migrations.AlterUniqueTogether(
            name='medialike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='medialike',
            name='media',
        ),
        migrations.RemoveField(
            model_name='medialike',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='ArticleLike',
        ),
        migrations.DeleteModel(
            name='ForumReponseLike',
        ),
        migrations.DeleteModel(
            name='ForumSujetLike',
        ),
        migrations.DeleteModel(
            name='MediaLike',
        ),
    ]
